version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: cognitiondb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U username -d cognitiondb"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://username:password@postgres:5432/cognitiondb?sslmode=disable
      JWT_SECRET: your-very-secure-jwt-secret-key-here
      PORT: 8080
    volumes:
      - ./web:/app/web

volumes:
  postgres_data: